import express from "express";
import authRoutes from "./auth";
import projectsRoutes from "./project";
import usersRoutes from "./user";
import tasksRoutes from "./task";
import invitationRoutes from "./invitation";
import { logActivity } from "../middlewares/activity";
const router = express.Router();
router.use("/auth", authRoutes);
router.use("/users", usersRoutes);
router.use("/projects", projectsRoutes, logActivity());
router.use("/tasks", tasksRoutes, logActivity());
router.use("/invitations", invitationRoutes);
export default router;
